# Generated by Django 4.2.23 on 2025-07-07 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='image',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='updated_on',
            new_name='updated_at',
        ),
    ]
